# Generated by Django 6.0.5 on 2026-05-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_client_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='Мастер'),
        ),
    ]
