# Generated by Django 6.0.5 on 2026-05-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Наша Мастерская', max_length=100)),
                ('description', models.TextField(verbose_name='О компании')),
                ('logo', models.ImageField(blank=True, upload_to='company/')),
                ('history', models.TextField(verbose_name='История по годам')),
                ('requisites', models.TextField(verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name_plural': 'О компании (одна запись)',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='employees/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField()),
                ('valid_until', models.DateField()),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
