# Generated by Django 6.0.5 on 2026-05-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_faq_news_review_vacancy_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос/Ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
