# Generated by Django 6.0.5 on 2026-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_review_options_remove_review_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Фото офиса/мастерской'),
        ),
    ]
